# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-21 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(max_length=5),
        ),
    ]
