# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-21 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer_app', '0002_auto_20180821_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
